name: "Jiri Hnidek"
description: "Personal page and blog"
author :
  name : Jiri Hnidek
  email : jiri.hnidek@tul.cz

url: "http://localhost:4000"

exclude: ['Gemfile', 'Gemfile.lock', 'README.md']
paginate: 4
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
highlighter: rouge
gems: ["jekyll-paginate"]

collections:
 wiki:
  output: true
  permalink: /wiki/:path/
